### ISSUE TITLE
encoding error writing unicode string to postgre

### ISSUE THREAD

**Issue by niphlod** [web2py/pydal#136] opened 2015-04-13 20:38 UTC
Taking the effort of posting here what is reported on web2py. I feel that those DAL bugs are never seen as a priority if not posted here.........

https://github.com/web2py/web2py/issues/910

**Comment by gi0baro** [comment] 2015-04-15 16:44
@niphlod I think we can patch this with py3 branch..

**Comment by niphlod** [comment] 2015-04-15 18:59
meaning it can't be fixed in python 2 ?

**Comment by gi0baro** [comment] 2015-04-15 19:10
Meaning that I've changed quite a lot of code involving encoding in py3 branch and it can be possibly yet fixed with that. 
Il 15/apr/2015 20:59, niphlod <notifications@github.com> ha scritto:meaning it can't be fixed in python 2 ?

**Comment by niphlod** [comment] 2015-04-15 19:30
as long as the fix works for python2, it's all fine. BTW: should I wait your merges before tackling a problem with unicode and mssql adapters ?

**Comment by gi0baro** [comment] 2015-04-16 12:40
My point was to not write the same code twice since as soon as py3 brach will pass all the tests i will propose a merge, and unicode-bytes related cose is changed from master.

**Comment by niphlod** [comment] 2015-04-16 12:49
let's wait then.

**Comment by ilvalle** [comment] 2015-05-04 16:31
@gi0baro do we have any test showing that this bug has been fixed after merging py3?

**Comment by gi0baro** [comment] 2015-05-04 22:52
@ilvalle I think we don't. We should write a py2py3 compatible test for bytes/unicode related stuffs.

**Comment by ilvalle** [comment] 2015-05-05 06:43
This is something we should do before releasing a new version

 Paolo

2015-05-05 0:52 GMT+02:00 Giovanni Barillari <notifications@github.com>:

**Comment by ilvalle** [comment] 2015-05-25 12:36
@gi0baro what is the status of this issue ?

**Comment by gi0baro** [comment] 2015-05-25 12:41
@ilvalle AFAIK it's pg8000 related only. I postponed the writing of some tests for the next revision.

**Comment by nursix** [comment] 2015-05-29 07:03
Hi - not sure whether this is the same problem, but BaseAdapter.expand() fails in Python 2.7 with a UnicodeEncodeError in line 935 if the expression is a unicode containing non-ASCII characters.

There is some urgency to this as it has gone into web2py 2.11.1-stable (sorry for pushing, but we really need this fixed in web2py, not just in pyDAL trunk - unfortunately the project separation has lead to serious delays before pyDAL fixes become available in web2py).

The particular case is:
"Icelandic Red Cross (Rauða krossinn)" is the expression, being an UTF-8 encoded str.

BaseAdapter.represent decodes it here:

        if PY2:
            if not isinstance(obj, bytes):
                obj = bytes(obj)
            try:
                obj.decode(self.db_codec) # <= here, db_codec being UTF-8
            except:
                obj = obj.decode('latin1').encode(self.db_codec)
        else:
            obj = to_unicode(obj)

...which converts it into a unicode.

But then, BaseAdapter.expand() does just try to str(rv) this unicode:

        else:
            rv = expression
        return str(rv) # <= here, not taking care of non-ASCII characters in unicodes

which will necessarily fail for any non-ASCII character in the unicode - but non-ASCII characters are the whole point of it being a unicode in the first place (!), so this seems wrong.

I added this as a workaround:

        if isinstance(rv, unicode):
            # Make sure non-ASCII code points are dealt with:
            return rv.encode(self.db_codec) # <= this produces an UTF-8 encoded str
        else:
            return str(rv)

which makes it work for me (having the db_codec being UTF-8). Surely this could still fail if db_codec is ASCII or Latin1 - but then that's correct as the DB wouldn't support it either.

Could you fix this, maybe quickly (since it affects web2py stable)? Many thanks.

**Comment by ilvalle** [comment] 2015-05-29 07:21
@nursix see my comment here https://github.com/web2py/web2py/issues/910#issuecomment-103580295
I can't test your workaround right now but as far as I remember it's related to pg8000 only. Can you double check using psycopg2 ?

**Comment by nursix** [comment] 2015-05-29 07:22
I am using psycopg2

**Comment by nursix** [comment] 2015-05-29 07:24
I outlined the cause of the problem above - obviously that is db-independent (and consequently I can reproduce it with SQLite and MySQL just as well).

**Comment by nursix** [comment] 2015-05-29 07:30
Yup, confirmed - the problem is right there in BaseAdapter.expand. If self.represent returns a unicode with non-ASCII characters, return str(rv) will necessarily fail (because it will assume ASCII).

**Comment by nursix** [comment] 2015-05-29 07:32
It probably is a different problem than the original issue discussed here - should I open a new issue then?

**Comment by ilvalle** [comment] 2015-05-29 07:36
The following works on both sqlite and mysql, what am I missing? Can you post a failing example ?
```
db=DAL(url)
db.define_table('tt', Field('vv', 'string'))
msg="Icelandic Red Cross (Rauða krossinn)"
id_i = db.tt.insert(vv=msg)
rows = db(db.tt.id==id_i).select(db.tt.vv)
row = rows.first()
print row.vv
```
it returns
```Icelandic Red Cross (Rauða krossinn)```

**Comment by nursix** [comment] 2015-05-29 07:41
Ahm - put this into the WHERE, not into the field (BaseAdapter.expand!!)

**Comment by nursix** [comment] 2015-05-29 07:44
>>> table = s3db.org_organisation
>>> query = table.name == "Icelandic Red Cross (Rauða krossinn)"
>>> db(query).select()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/objects.py", line 1986, in select
    return adapter.select(self.query,fields,attributes)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1248, in select
    sql = self._select(query, fields, attributes)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1135, in _select
    sql_w = ' WHERE ' + self.expand(query) if query else ''
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 916, in expand
    rv = op(first, second, **optional_args)
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 810, in EQ
    self.expand(second, first.type))
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/adapters/base.py", line 938, in expand
    return str(rv)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf0' in position 25: ordinal not in range(128)

**Comment by nursix** [comment] 2015-05-29 08:06
Ok, I think the psychopg2 problem can be explained here (in postgres adapter):

    def adapt(self, obj):
        if self.driver_name == 'psycopg2':
            rv = psycopg2_adapt(obj).getquoted()
            if isinstance(rv, bytes):
                return rv.decode("utf8") # <= why decode the str?
            return rv
        elif self.driver_name == 'pg8000':
            return "'%s'" % obj.replace("%", "%%").replace("'", "''")
        else:
            return "'%s'" % obj.replace("'", "''")

I'm not sure why it should convert into a unicode here? Isn't adapt expected to return an encoded str?

**Comment by nursix** [comment] 2015-05-29 08:08
It should probably be the other way around:

    if isinstance(rv, unicode):
        return rv.encode("utf-8")

No?

**Comment by nursix** [comment] 2015-05-29 08:09
Or probably rv.encode(self.db_codec) (makes more sense than to assume utf-8)

**Comment by nursix** [comment] 2015-05-29 08:11
Yup, this fixes it for postgres/psychopg2:

    def adapt(self, obj):
        if self.driver_name == 'psycopg2':
            rv = psycopg2_adapt(obj).getquoted()
            if isinstance(rv, unicode):
                return rv.encode(self.db_codec)
            return rv
        elif self.driver_name == 'pg8000':
            return "'%s'" % obj.replace("%", "%%").replace("'", "''")
        else:
            return "'%s'" % obj.replace("'", "''")

(in adapters/postgres.py)

**Comment by ilvalle** [comment] 2015-05-29 08:15
The issue is related to the postgres adapter because on both mysql and sqlite the following works printing what expected:
```
db=DAL(url)
db.define_table('tt', Field('vv', 'string'))
msg="Icelandic Red Cross (Rauða krossinn)"
id_i = db.tt.insert(vv=msg)
rows = db(db.tt.vv==msg).select(db.tt.vv)
row = rows.first()
print row.vv
```
Instead of guessing the error line, I suggest writing a failing example and debug it step by step.

**Comment by nursix** [comment] 2015-05-29 08:18
I gave you the failing example in my first post, no?

**Comment by nursix** [comment] 2015-05-29 08:25
Ok, if you don't want suggestions, then I'm not going to debug any further.

Fact is, if self.represent returns a unicode - for whatever reason - then the last line in self.expand will fail. It is possible to make it fail-safe by catching unicodes as I suggested, but surely you can also go through the adapters and try to make sure they always return an encoded str. For postgres, the above fix works.

Whatever your solution finally will be - since the problem affects web2py stable, will you publish the fix soon?

**Comment by ilvalle** [comment] 2015-05-29 08:33
Unfortunately not soon, I can post a PR containing the fix and few unitest in a week or so.
Regarding the fix, it should be on the adapter and it should work for both python 2.* and 3.*

**Comment by nursix** [comment] 2015-05-29 08:39
Ok, this is a bit disappointing :(

So we need to recommend our users to not deploy web2py-2.11.1 because the PyDAL is broken. That makes it a bit difficult, because getting an older stable requires them to dig manually rather than using automated setup scripts - which is a bit of a blocker for us.

But ok, so be it...

**Comment by mdipierro** [comment] 2015-05-29 11:59
Thank you Dominic for spotting this so soon.
This very bad. We wanted to launch at the conference today and this is a major problem.

So for now I have reverted the “stable” online version so 2.10.4. The website still says 2.11.1

Massimo

**Comment by mdipierro** [comment] 2015-05-29 11:59
self.represent should NEVER return unicode. Unless it is on GAE perhaps.

**Comment by niphlod** [comment] 2015-05-29 13:20
the whole thing is debatable, but in the need of a quickfix, the problem seems to surface just because "bytes" in py2 and py3 are different things. 
Given that the only change was indeed within postgresql expand, and that in py3 the problem doesn't seem to be there, I'm preparing a quickfix PR that will re-establish "things as they were" just for PY2. We can elaborate on the following week(s) if we need to reorder some thoughts.

**Comment by nursix** [comment] 2015-05-29 13:23
Hello Massimo--

Thanks for reverting the "stable". 

However, I've already posted a recommendation to stick with 2.10.4 for now, and Fran has modified the installation scripts to deploy PyDAL 15.03 until this is fixed - so I think from our side, things are sorted for now.

**Comment by nursix** [comment] 2015-05-29 13:36
@niphlod Note that PostgreSQLAdapter.adapt seems to deliberately decode the str into a unicode for psychopg2 - and why should it do that? If, like Massimo says, represent is supposed to NEVER return a unicode, then this decode should probably rather be an encode /if/ rv is indeed a unicode - so maybe the right idea, but just implemented the wrong way around?

Just a thought...

**Comment by niphlod** [comment] 2015-05-29 13:42
no worries. it seems spurious because the code just tested fails even in py3. 
I think it's merely a bug, but let's don't get cranky for small time issues ^_^' . let me work on it and get back here.

**Comment by gi0baro** [comment] 2015-05-29 15:06
I'm sorry about the mess, I think we should definitely include some unicode tests inside pyDAL.
@niphlod should we create a separated branch for this to be included in web2py or build a new bugfix release? what do you think?

**Comment by niphlod** [comment] 2015-05-29 15:11
imho pull #202 in, make 2015.05.29, release 2.11.2 with 2014.05.29. 
We can discuss further for py3-only issues dealing with unicode params with relative calm.
After all, py3 support in pydal is still quite experimental.

**Comment by niphlod** [comment] 2015-05-29 15:20
BTW (just to keep things on but ONLY for PY3)... I don't think we should go with psycopg2_adapt any longer, because it feels to me that is useful only to register new types AND to be used in conjunction with parametrized statements. 
Until now we "cheated" for whatever reason using it (i.e. it feels more "safer" to rely on a psycopg2 routine insted of using the "our-own-baked" solution that seems not to give issues on other backends) but with py3 returning bytes "by design" and web2py building the query on its own it clashes (big time).

**Comment by nursix** [comment] 2015-06-01 06:19
Many thanks @niphlod , web2py-2.11.2 with PyDAL 15.05.29 are passing all Sahana tests, so from our side the problem seems solved. I didn't open this issue, though - so not my call whether to close it.

**Closed** 2015-06-26 13:13 UTC
Labels: bug
