### ISSUE TITLE
Double-inheritance fail

### ISSUE THREAD

**Issue by RekGRpth** [web2py/pydal#323] opened 2016-01-27 09:32 UTC
For example, I have 4 classes: Abonent, Person, Company and Provider.
Person and Company are (sublasses of) Abonents, and Provider is (subclasses of) Company.
In django I can write
```python
class Abonent(models.Model): pass
class Person(Abonent): pass
class Company(Abonent): pass
class Provider(Company): pass
```
and in wep2py I want write
```python
db.define_table('abonent')
db.define_table('person', Field('abonent', db.abonent), primarykey=['abonent'])
db.define_table('company', Field('abonent', db.abonent), primarykey=['abonent'])
db.define_table('provider', Field('company', db.company), primarykey=['company'])
```
but it fails

**Comment by niphlod** [comment] 2016-01-27 09:56
when using custom pkeys, referencing fields must use the reference tablename.fieldname format.

**Comment by RekGRpth** [comment] 2016-01-27 10:24
I tryed this
```python
db.define_table('abonent')
db.define_table('person', Field('abonent', db.abonent), primarykey=['abonent'])
db.define_table('company', Field('abonent', db.abonent), primarykey=['abonent'])
db.define_table('provider', Field('company', db.company.abonent), primarykey=['company'])
```
and this
```python
db.define_table('abonent')
db.define_table('person', Field('abonent', type='reference abonent'), primarykey=['abonent1'])
db.define_table('company', Field('abonent', type='reference abonent'), primarykey=['abonent1'])
db.define_table('provider', Field('company', type='reference company.abonent'), primarykey=['company1'])
```
with same fail results

**Comment by RekGRpth** [comment] 2016-01-27 10:26
May be there is another way to to this (like django) in web2py?

**Comment by niphlod** [comment] 2016-01-27 10:28
uhm. what specific table definition fails ? also, are you sure that a foreign key is also a primary key (provider table) ?

PS: this isn't at all inheritance. this is 1:M relationships.

**Comment by RekGRpth** [comment] 2016-01-27 10:31
How I can organize inheritance (like django) in web2py? I have not any tables in database yet.

**Comment by niphlod** [comment] 2016-01-27 10:35
you keep talking assuming django is general knowledge. Read the docs first, and open bugs later ?

**Comment by RekGRpth** [comment] 2016-01-27 10:43
I read entire book

**Comment by niphlod** [comment] 2016-01-27 10:49
including that section, which doesn't resemble at all the pieces of code you're trying to make it work ?

**Comment by RekGRpth** [comment] 2016-01-27 11:32
if I write
```python
db.define_table('abonent')
db.define_table('person', db.abonent)
db.define_table('company', db.abonent)
db.define_table('provider', db.company)
```
then web2py creates copy of fields of abonent into person and company tables, and copy of fields of company into provider table. And when I insert a row into provider table, then abonent table does not contain this row

In django inheritance works follow: when I insert a row into provider table, then it is inserted in company and abonent also

**Comment by niphlod** [comment] 2016-01-27 12:02
perfect, then it's definitely NOT a bug.
inheritance in web2py means that you can avoid defining the same fields for different tables. 
 pydal is not an ORM.
if you want an insert to happen in multiple tables, the best solution would be to use [callbacks](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#callbacks-on-record-insert--delete-and-update).
I'll close this as its not a bug. Feel free to ask for directions on the [official forum](https://groups.google.com/forum/#!forum/web2py)

**Closed by niphlod** 2016-01-27 12:02 UTC
