### ISSUE TITLE
MySQL - #1071 - Specified key was too long; max key length is 767 bytes   

### ISSUE THREAD

**Issue by pgastinger** [web2py/pydal#186] opened 2015-05-12 06:13 UTC
Hi, 

I wanted to migrate from sqlite to mysql and had following problem. I tracked it down and found following:

This is my table definition:
db.define_table('testtable',
                Field('teststring','string',unique=True)
                )

which translates to following mysql-code:
CREATE TABLE testtable(
    id INT AUTO_INCREMENT NOT NULL,
    teststring VARCHAR(512) UNIQUE,
    PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET utf8;

and following error message:
#1071 - Specified key was too long; max key length is 767 bytes 
 
It seems that the unique=True causes that kind of problem. If I omit the unique=True, it works:
db.define_table('testtable2',
                Field('teststring','string')
                )
CREATE TABLE testtable2(
    id INT AUTO_INCREMENT NOT NULL,
    teststring VARCHAR(512),
    PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET utf8;

The varchar(512) is too long, if I reduce it to a varchar(255) it works (>= 256 does not work).

I am using web2py 2.10.4 and mysql 5.5.39 (MySQL Community Server (GPL)) on RHEL6. Probably a pretty easy fix would be to translate a dal string into a varchar(255), but I blame Mysql here ...

**Comment by ilvalle** [comment] 2015-05-12 06:29
the issue is due to a limit of innodb. As you described, you can either set
the length of the field to 255 or play with the innodb parameters of your
mysql installation (iff you have the permissions). I suggest the former as
follow:
db.define_table('testtable',
Field('teststring','string', length=255, unique=True)
)

 Paolo

2015-05-12 8:13 GMT+02:00 Peter Gastinger <notifications@github.com>:

**Comment by gi0baro** [comment] 2015-07-02 13:34
@pgastinger @ilvalle may I close this?

**Closed** 2015-12-04 17:07 UTC
