### ISSUE TITLE
duplicated function on mongoDB adapter

### ISSUE THREAD

**Issue by franciscocosta** [web2py/pydal#269] opened 2015-08-10 14:19 UTC
function CONTAINS is causing trouble because is duplicated
If I comment the one at line 589 everything works fine

**Comment by stephenrauch** [comment] 2015-08-10 14:39
This likely has the same root cause as #268.

**Comment by gi0baro** [comment] 2015-08-16 11:27
I'm closing this since something went wrong with web2py release, is not pydal related.

**Closed by gi0baro** 2015-08-16 11:27 UTC
Labels: invalid
