### ISSUE TITLE
recursive queries break with lazy tables in recent pydal versions

### ISSUE THREAD

**Issue by mdipierro** [web2py/pydal#262] opened 2015-08-04 15:21 UTC
https://groups.google.com/forum/#!topic/web2py/_5TzZSxYufQ

**Comment by ilvalle** [comment] 2015-08-17 14:29
I reproduced the issue on https://github.com/web2py/pydal/tree/v15.05.29 (the release used by web2py 2.11.2) however according to my tests  master pydal seams fixed.

https://github.com/web2py/pydal/commit/86a8c7cf2e1a3679dc5e80c70decb512721fb0ec fixed it.

**Comment by gi0baro** [comment] 2015-08-18 12:55
I'm closing this since something went wrong with web2py release, is not pydal related.

**Closed by gi0baro** 2015-08-18 12:55 UTC
Labels: invalid
